### ISSUE TITLE
cannot find -lteec

### ISSUE THREAD

**Issue by yingkailiang** [jenswi-linaro/lcu14_optee_hello_world#13]
I follow the instructions and compiles the helloworld example. Following is the compile error I get. Any idea how to address this issue? I saw similar issue reports in  #8, but there is no solution to this issue.
Thanks for any suggestion. 

make -C host CROSS_COMPILE=/home/kying/Develop/optee/optee_hello_world/../toolchains/aarch64/bin/aarch64-linux-gnu-
make[1]: Entering directory `/home/kying/Develop/optee/optee_hello_world/host'
/home/kying/Develop/optee/optee_hello_world/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc -lteec -L/home/kying/Develop/optee/optee_hello_world/../optee_client/out/export/lib -o hello_world hello_world.o
/home/kying/Develop/optee/toolchains/aarch64/bin/../lib/gcc/aarch64-linux-gnu/4.9.1/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /home/kying/Develop/optee/optee_hello_world/../optee_client/out/export/lib/libteec.so when searching for -lteec
/home/kying/Develop/optee/toolchains/aarch64/bin/../lib/gcc/aarch64-linux-gnu/4.9.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lteec
collect2: error: ld returned 1 exit status
make[1]: *** [hello_world] Error 1
make[1]: Leaving directory `/home/kying/Develop/optee/optee_hello_world/host'
make: *** [all] Error 2

**Comment by vchong** [comment]
You need to build optee_client and optee_os first. The error seems to indicate you haven't built optee_client or it's not in the correct path. Have you performed step 2 in the instructions? All the repos need to be under `<optee-workspace>`. In your case, that's `/home/kying/Develop/optee`.

Also, if you're using the latest optee_os, which is recommended, you need to make the following change:
`export TA_DEV_KIT_DIR=$PWD/../optee_os/out/arm/export-ta_arm32`

**Comment by yingkailiang** [comment]
I have built the optee_client and follow the instruction step 2. I can run qemu in build folder by typing "make all run". 
After follow your @vchong  suggestion, I still got the same error message. I can see libteec.so in optee_client/out/export/lib folder. I try to manually add this folder to $LD_LIBRARY_PATH, it does not work as well. 
Do you have any other suggestion?

**Comment by vchong** [comment]
Ok. I think I found the issue. I think QEMU is still arm only, not aarch64, so do a `make clean` first, then `export HOST_CROSS_COMPILE=$PWD/../toolchains/aarch32/bin/arm-linux-gnueabihf-`, and then `make` again.

**Comment by yingkailiang** [comment]
It works. Thanks for your help.
