### ISSUE TITLE
--gc-section Destroys TA

### ISSUE THREAD

**Issue by bafATsit** [jenswi-linaro/lcu14_optee_hello_world#20]
Hillo,

I use this HelloWorld as a starting point for my own project.
(Thanks for sharing.)

My project needs to set the following flags in ta/sub.mk
`CFLAGS += -ffunction-sections -fdata-sections`
`LDFLAGS += --gc-section`
Unfortunately, this totally destroys the TA HelloWorld.
The TA is build but, the optee_os cannot load it. It throws Errors.

This flag seems to strip off just way to much code.
HelloWorld TA size with `--gc-section` set is 68K (elf: 8K).
HelloWorld TA size without flag is 116K (elf: 240K).

Is there any chance to set these flags within this build process?

edit:
Actually, this is a quite common problem with --gc-sections flag, that section which are not in the call-tree of the main() program are removed, although they shouldn't. This may happen to start-up code or interrupt-vectors.
To prevent this, one can use a linker-script and set ENTRY(...), e.g. ENTRY(_reset_code).

Is this possible here?
What may the ENTRY points be here?

**Comment by bafATsit** [comment]
I tried to insert KEEP() command in ta/ta.lds but, without success.
gcc-nm doesn't list any of these symbols.
> OUTPUT_FORMAT("elf32-littlearm")`
> OUTPUT_ARCH(arm)
> PHDRS {
> exec PT_LOAD FLAGS (5);
> rodata PT_LOAD FLAGS (4);
> rwdata PT_LOAD;
>  dyn PT_DYNAMIC;
> }
> SECTIONS {
> .ta_head : {\*(.ta_head)} :exec
> .text : {
> \*(.text .text.\*)
> \*(.stub)
> \*(.glue_7)
> \*(.glue_7t)
> \*(.gnu.linkonce.t.\*)
> \*(.vfp11_veneer)
>  KEEP(\*(.TA_CreateEntryPoint))
>  KEEP(\*(.TA_DestroyEntryPoint))
>   KEEP(\*(.TA_OpenSessionEntryPoint))
>   KEEP(\*(.TA_InvokeCommandEntryPoint))
>   KEEP(\*(.TA_CloseSessionEntryPoint))
>  }

Is this the right linker script to insert KEEP()?
Is the KEEP() command in the right place?

**Comment by jenswi-linaro** [comment]
Hi,

This example is getting a bit outdated, I think you would be better off looking at the test TAs that we have in https://github.com/OP-TEE/optee_test, for instance https://github.com/OP-TEE/optee_test/tree/master/ta/crypt
