### ISSUE TITLE
About the file user_ta_header_defines.h

### ISSUE THREAD

**Issue by Tigerly** [jenswi-linaro/lcu14_optee_hello_world#23]
I'm kind of confuse about the file - user_ta_header_defines.h.
It looks like a configure file for the op-tee, however, it seems that nobody include it.
Also, in that file, it says "do not modify the file name".

I'm curious about what this file is used for? whether we can get rid of it?

Thanks in advance!

**Comment by vchong** [comment]
This project has been superseded by https://github.com/linaro-swg/optee_examples.

In any case, the header file is used by at least https://github.com/OP-TEE/optee_os/blob/master/ta/arch/arm/user_ta_header.c#L31 to get some info about the TA. It wouldn't work properly if removed, so why do you want to get rid of it?

**Comment by Tigerly** [comment]
got it. Thank you!
I'm trying to build my own .ta file, but I'm not sure how does "user_ta_header_defines.h" get involved in the compilation. Would it be possible to share the compile stuff about "user_ta_header_defines.h"?

**Comment by vchong** [comment]
I'm not sure of the exact details either, but .ta files are built not just using the files contained in this repository. They also require the TA development kit, which is built when optee_os is built. The TA dev kit is in optee_os/out/arm-plat-<platform>/export-ta_arm{64,32}. In export-ta_arm{64,32}/src, there's a user_ta_header.c file, which includes user_ta_header_defines.h. You can probably check out the files in export-ta_arm{64,32}/mk/ for the makefiles to build .ta files.
