### ISSUE TITLE
How to build this TA

### ISSUE THREAD

**Issue by fanguannan0706** [jenswi-linaro/lcu14_optee_hello_world#3]
I followed the steps at https://github.com/OP-TEE/optee_os and bulit the OP-TEE using FVP.Now, I want to bulid this TA, I tried to run the makefile ,but it didn't work. Please tell me how to build this TA. Thank you very much.

**Comment by jenswi-linaro** [comment]
Hi,

It compiles with the latest commit from https://github.com/OP-TEE/optee_os and https://github.com/OP-TEE/optee_client with the following commands:
```
# Make sure the cross compiler is in the PATH
export PATH="${HOME}/armv7-toolchain/gcc-linaro-arm-linux-gnueabihf-4.8-2013.12_linux/bin:${PATH}"
# Make TA_DEV_KIT_DIR point to the export-user_ta directory that was created
# when optee_os was built
export TA_DEV_KIT_DIR=${HOME}/work/op-tee/out-os-qemu/export-user_ta
# Make TEEC_EXPORT point to the export directory that was created when
# optee_client was built
export TEEC_EXPORT=${HOME}/work/op-tee/out-client-armv7/export
# Select cross compiler for the user space program
export HOST_CROSS_COMPILE=arm-linux-gnueabihf-
# Select cross compiler for the trusted application
export TA_CROSS_COMPILE=arm-linux-gnueabihf-

make
```

**Comment by fanguannan0706** [comment]
Hi,
There is something wrong again:

/home/fanguannan/devel/fvp_optee/optee_client/out/export/lib/libteec.so: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:19: recipe for target 'hello_world' failed
make[1]: *** [hello_world] Error 1
make[1]: Leaving directory '/home/fanguannan/devel/lcu14_optee_hello_world-master/host'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jenswi-linaro** [comment]
Hi,

Sorry, I missed that you're running normal world in Aarch64. Try the following instead:
```
# Make sure the cross compilers are in the PATH
export PATH="${HOME}/aarch64-toolchain/gcc-linaro-aarch64-linux-gnu-4.8-2013.11_linux/bin:${PATH}"
export PATH="${HOME}/armv7-toolchain/gcc-linaro-arm-linux-gnueabihf-4.8-2013.12_linux/bin:${PATH}"
# Make TA_DEV_KIT_DIR point to the export-user_ta directory that was created
# when optee_os was built
export TA_DEV_KIT_DIR=${HOME}/work/op-tee/out-os-fvp/export-user_ta
# Make TEEC_EXPORT point to the export directory that was created when
# optee_client was built
export TEEC_EXPORT=${HOME}/work/op-tee/out-client-fvp/export
# Select cross compiler for the user space program
export HOST_CROSS_COMPILE=aarch64-linux-gnu-
# Select cross compiler for the trusted application
export TA_CROSS_COMPILE=arm-linux-gnueabihf-

make
```

Note the change of HOST_CROSS_COMPILE and the additional PATH

**Comment by fanguannan0706** [comment]
o(╯□╰)o：

make -C ta CROSS_COMPILE=/home/fanguannan/devel/fvp_optee/toolchains/gcc-linaro-arm-linux-gnueabihf-4.8-2013.12_linux/bin/arm-linux-gnueabihf-
make[1]: Entering directory '/home/fanguannan/devel/lcu14_optee_hello_world-master/ta'
  CC      hello_world_ta.o
gcc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
gcc: error: unrecognized command line option ‘-mthumb’
gcc: error: unrecognized command line option ‘-mthumb-interwork’
gcc: error: unrecognized command line option ‘-mlong-calls’
gcc: error: unrecognized command line option ‘-mno-apcs-float’
gcc: error: unrecognized command line option ‘-mfloat-abi=soft’
gcc: error: unrecognized command line option ‘-mno-unaligned-access’
/home/fanguannan/devel/fvp_optee/optee_os/out/arm32-plat-vexpress/export-user_ta/mk/compile.mk:121: recipe for target 'hello_world_ta.o' failed
make[1]: *** [hello_world_ta.o] Error 1
make[1]: Leaving directory '/home/fanguannan/devel/lcu14_optee_hello_world-master/ta'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jenswi-linaro** [comment]
This looks like an error we have fixed recently.
Are you using latest from  https://github.com/OP-TEE/optee_os?

**Comment by fanguannan0706** [comment]
I have built optee for some days, I'll try to update it.

**Comment by fanguannan0706** [comment]
Hi,
I have compiled the ta.Now, I find I have no idea how to run it.Can you tell me what to do now ?

**Comment by jenswi-linaro** [comment]
You need to put `8aaaf200-2450-11e4-abe20002a5d5c51b.ta` in `/lib/teetz/` in the target file system and also put the `hello_world` executable somewhere in the file system (`/bin` for instance).

Have you been able to boot OP-TEE together with a kernel driver and tee-supplicant?

**Comment by broadskyflyer** [comment]
Now I understand the architecture of optee_client, optee_os, and ta. But I don't know how to support host kenel to directly use the function of ta. For example, when OS is booting, and tee-supplicant isn't working, is there any mechanism to call a ta function?

**Comment by jenswi-linaro** [comment]
tee-supplicant has to run to be able to load a TA, so without the supplicant running not much can be done.

**Comment by broadskyflyer** [comment]
Why not to build some TAs within OPTEE_OS?

**Comment by fanguannan0706** [comment]
Hi,
It's me again, now I can execute the example successfully. And then, I'd like to add some new libraries to the optee, so I can build some trusted applications using them. But I don't know how to do this.

**Comment by jenswi-linaro** [comment]
The easiest way to get started would be to include the source of the library in the TA. If you really want a separate library to link against you'll need to build it with the same compiler flags as are used for libutee and friends.

**Comment by fanguannan0706** [comment]
Ok, I'll try to build the library and find how to set the flags. I hope it's not too hard, is it?

**Comment by fanguannan0706** [comment]
I tried to add a library , and when I build the secure world , it can't work, because "all warnings being treated as errors", is it necessary to be so strict?

**Comment by jenswi-linaro** [comment]
All code we use in OP-TEE need to compile without warnings, but you can turn it off with NOWERROR=1 for your own purposes.

**Comment by fanguannan0706** [comment]
I have bulit some libraries successfully. But when I build my ta, it info "undefined reference" to my function(I have include the head files), I guess it because I used some my own lib or something else. So, how can I solve this problem?

**Comment by jenswi-linaro** [comment]
You need to find a way to pass `-L<path-to-your-lib> -l<your-lib>` when linking the TA.

**Comment by fanguannan0706** [comment]
Hi, I want to write a kernel module and I will call the functions in "tee_kernel_api.c", but there is something wrong : "kernel panic - not syncing : BUG!" It makes me confused, why the TEE_TZ_DEVICE_NAME is defined "opteearm3200"? it may be "opteearmtz00". And if the functions can work on the 64-bit platform?

**Comment by thinhlevinh** [comment]
How can I have this kind of file?

You need to put 8aaaf200-2450-11e4-abe20002a5d5c51b.ta in /lib/teetz/ in the target file system and also put the hello_world executable somewhere in the file system (/bin for instance).

Thanks,
ThinhLe

**Comment by JunKetty** [comment]
Hi,I have compiled the ta. I want to run it. There you said that
You need to put 8aaaf200-2450-11e4-abe20002a5d5c51b.ta in /lib/teetz/ in the target file system and also put the hello_world executable somewhere in the file system (/bin for instance).
But I don't know where the /lib/teetz/ is. Is there anyone can help me?

**Comment by Miraje** [comment]
Hi @JunKetty, I don't know which board you are using, but I'm using the Juno Board, and in my case it is the `/lib/optee_armtz/` folder but I believe for you it should be the same one. This folder is located in the board file system.

**Comment by JunKetty** [comment]
Hi @Miraje , I don't use any board, only run it on QEMU. 
Thanks for your answers

**Comment by vchong** [comment]
If you go to https://github.com/OP-TEE/optee_os/blob/master/README.md, follow the instructions for QEMU, and are using somewhat recent code, it should automatically build a hello world TA. Not this one, but https://github.com/linaro-swg/hello_world, which is based on this one but is the 'officially' maintained version. Once you boot up QEMU and get to the command prompt, you should be able to see the *.ta file in `/lib/optee_armtz/` and hello_world in `/bin/`.

HTH

**Comment by JunKetty** [comment]
Hi @vchong I had  followed the instructions for QEMU according to  https://github.com/OP-TEE/optee_os/blob/master/README.md, and also built the hello world follow https://github.com/linaro-swg/hello_world, but there isn't 8aaaf200-2450-11e4-abe20002a5d5c51b.ta in /lib/teetz/  or hello_world in /bin/. 
Thanks!
