### ISSUE TITLE
Some Questions About Kernel Module

### ISSUE THREAD

**Issue by fanguannan0706** [jenswi-linaro/lcu14_optee_hello_world#5]
Hi, I want to write a kernel module and I will call the functions in "tee_kernel_api.c", but there is something wrong : "kernel panic - not syncing : BUG!" It makes me confused, why the TEE_TZ_DEVICE_NAME is defined "opteearm3200"? it may be "opteearmtz00". And if the functions can work on the 64-bit platform?

**Comment by jenswi-linaro** [comment]
Hi,

Please repost this in https://github.com/OP-TEE/optee_linuxdriver with some more details on which function you're calling etc.

Regards Jens
