### ISSUE TITLE
how to make .bin target

### ISSUE THREAD

**Issue by roman3017** [jenswi-linaro/lcu14_optee_hello_world#9]
I am having a trouble compiling .bin target required by .ta target:

make -C host CROSS_COMPILE=/opt/toolchains/gcc-linaro-arm-linux-gnueabihf-4.9-2014.08_linux/bin/arm-linux-gnueabihf-
make[1]: Entering directory `/local/optee_hello_world/host'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/local/optee_hello_world/host'
make -C ta CROSS_COMPILE=/opt/toolchains/gcc-linaro-arm-linux-gnueabihf-4.9-2014.08_linux/bin/arm-linux-gnueabihf-
make[1]: Entering directory `/local/optee_hello_world/ta'
Makefile:10: warning: overriding commands for target `8aaaf200-2450-11e4-abe20002a5d5c51b.ta'
/local/optee_os/out/arm-plat-bcm/export-user_ta/mk/link.mk:60: warning: ignoring old commands for target `8aaaf200-2450-11e4-abe20002a5d5c51b.ta'
make[1]: *** No rule to make target `8aaaf200-2450-11e4-abe20002a5d5c51b.bin', needed by `8aaaf200-2450-11e4-abe20002a5d5c51b.ta'.  Stop.
make[1]: Leaving directory `/local/optee_hello_world/ta'
make: *** [all] Error 2

Commenting out .ta target (three lines below) from ta/Makefile works. Is this intended?

$(BINARY).ta: $(BINARY).bin
	rm -f $@
	cat faked_armv7_uta_signed_header.bin $< > $@

**Comment by jenswi-linaro** [comment]
I just merged a pull request from @oliviermartin that fixes this.

**Comment by roman3017** [comment]
Thanks
